### PR TITLE
Fixes upload example and test to match online

### PR DESCRIPTION
**Pull request by FokkeZB**
Fixes https://github.com/zapier/zapier-platform-core/issues/35

I tried using `z.request` instead but with no luck. I tried various things, including `z.request({url, raw:true}).then(res => { .. formData.append('file', res.body .. ])` but apart from more code/complexity it didn't work as well.

### CODE REVIEW

**Comment by FokkeZB** [comment]
retest

**Comment by BrunoBernardino** [comment]
@FokkeZB a couple of things since you're on it (or leave it to me and I'll update this PR):

1. Please add a `travis-setup.sh` file, with:
```bash
ZAPIER_FILE='/home/travis/.zapierrc'
touch $ZAPIER_FILE
echo "{
  \"deployKey\": \"$ZAPIER_DEPLOY_KEY\"
}" > $ZAPIER_FILE
```
2. Please update `.travis.yml` to:
```json
language: node_js
node_js:
  - "4.3.2"
before_script: bash ./travis-setup.sh && npm install -g zapier-platform-cli
script: zapier test
notifications:
  email: false
```
3. Please use [`got`](https://github.com/sindresorhus/got) instead of `request` as it's lighter and promise-based (props to @xavdid for the suggestion)

I've done the setup in Travis for that to work, and the tests here then should pass.

**Comment by FokkeZB** [comment]
Thanks @BrunoBernardino!

I've added the Travis changes.

For `got`, I didn't get that working with `got.stream(bundle.inputData.file)`. Any idea what I'm doing wrong here? Wouldn't it be better to see if we can get it to work with `z.request()` as that would also make the requests appear in GL and save a dependency?

**Comment by BrunoBernardino** [comment]
Great point. Let's see if we can use `z.request`, otherwise keep it as it is, then.

**Pull request merged**
